### ISSUE TITLE
add info

### ISSUE THREAD

**Issue by aksingh-08** [akscoder082003/Vigenere-Cipher#1]
add the comments on both Encryption and Decryption files.

**Comment by Den1f** [comment]
hey @akscoder082003 , can you please assign this issue to me? Would love to work on this.

**Comment by aksingh-08** [comment]
> hey @akscoder082003 , can you please assign this issue to me? Would love to work on this.

sure!

**Comment by Den1f** [comment]
@akscoder082003 hey,  I have created a PR.
